#!/usr/bin/env python3
"""Writes docs/release/store-metadata/<lang>.md (App Store Connect copy, 12 languages) from
scripts/store-metadata/metadata.json and enforces App Store Connect limits.

  python3 scripts/store-metadata/build.py          # check limits + write
  python3 scripts/store-metadata/build.py --check  # CI: limits + files up to date
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(ROOT, 'docs', 'release', 'store-metadata')
LANGS = ['tr', 'en', 'de', 'es', 'fr', 'pt', 'ru', 'ar', 'hi', 'bn', 'ja', 'zh-Hans']
LIMITS = {'name': 30, 'subtitle': 30, 'promotionalText': 170, 'description': 4000, 'keywords': 100, 'whatsNew': 4000}
# Guideline 2.3.7: no other apps' or companies' names in keywords.
BANNED_KEYWORDS = {'spotify', 'youtube', 'instagram', 'x', 'facebook', 'google', 'apple', 'arcore', 'tiktok'}
TITLES = [('name', 'Name'), ('subtitle', 'Subtitle'), ('promotionalText', 'Promotional Text'),
          ('description', 'Description'), ('keywords', 'Keywords'), ('whatsNew', "What's New in This Version")]


def problems_for(lang, entry):
    problems = []
    for field, limit in LIMITS.items():
        value = entry.get(field, '')
        if not value.strip():
            problems.append(f'{lang}: {field} is empty')
        elif len(value) > limit:
            problems.append(f'{lang}: {field} is {len(value)} characters (limit {limit})')
    keywords = entry.get('keywords', '').split(',')
    if any(k != k.strip() or not k for k in keywords):
        problems.append(f'{lang}: keywords must be comma separated without spaces or empty items')
    if len({k.lower() for k in keywords}) != len(keywords):
        problems.append(f'{lang}: duplicate keywords')
    banned = BANNED_KEYWORDS & {k.lower() for k in keywords}
    if banned:
        problems.append(f'{lang}: trademarks in keywords {sorted(banned)}')
    return problems


def render(lang, entry):
    lines = [f'# LociAR App Store copy — {lang} ({entry["storeLocale"]})', '',
             '<!-- Generated by scripts/store-metadata/build.py from metadata.json; edit the JSON, not this file. -->', '']
    for field, title in TITLES:
        value = entry[field]
        lines += [f'## {title} ({len(value)}/{LIMITS[field]})', '', '```text', value, '```', '']
    return '\n'.join(lines)


def main():
    check = '--check' in sys.argv
    with open(os.path.join(HERE, 'metadata.json'), encoding='utf-8') as f:
        data = json.load(f)
    problems = [f'missing language {lang}' for lang in LANGS if lang not in data]
    for lang in LANGS:
        if lang in data:
            problems += problems_for(lang, data[lang])
    if problems:
        print('\n'.join(problems))
        sys.exit(1)
    outputs = {os.path.join(OUT, f'{lang}.md'): render(lang, data[lang]) for lang in LANGS}
    if check:
        stale = [p for p, text in outputs.items() if not os.path.exists(p) or open(p, encoding='utf-8').read() != text]
        if stale:
            print('Out of date (run python3 scripts/store-metadata/build.py):', *stale, sep='\n  ')
            sys.exit(1)
        print(f'OK: store copy for {len(LANGS)} languages within limits')
        return
    os.makedirs(OUT, exist_ok=True)
    for path, text in outputs.items():
        with open(path, 'w', encoding='utf-8') as f:
            f.write(text)
    print(f'Wrote {len(outputs)} files to {os.path.relpath(OUT, ROOT)}')


if __name__ == '__main__':
    main()
