// Writes emulator-only configuration for the integration suite: Apple revocation settings pointing
// at the local stub in security.test.mjs, a GIPHY host pointing at the stub in callables.test.mjs, and a throwaway P-256 key generated on every run. The
// files are gitignored and never deployed (*.local is in firebase.json's ignore list; the
// .env.demo-lociar file only applies to the demo project). Existing files written by someone else
// are left alone.
import { generateKeyPairSync } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const MARKER = '# generated by functions/test/integration/prepare-env.mjs (emulator only)';
export const APPLE_STUB_PORT = 9871;
export const GIPHY_STUB_PORT = 9872;

function writeOwned(path, body) {
  const url = new URL(`../../${path}`, import.meta.url);
  if (existsSync(url) && !readFileSync(url, 'utf8').startsWith(MARKER)) {
    throw new Error(`functions/${path} exists and was not written by prepare-env.mjs; move it away to run the emulator suite.`);
  }
  writeFileSync(url, `${MARKER}\n${body}\n`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { privateKey } = generateKeyPairSync('ec', { namedCurve: 'prime256v1' });
  const pem = privateKey.export({ type: 'pkcs8', format: 'pem' }).toString().trim().replace(/\n/g, '\\n');
  writeOwned('.secret.local', [`APPLE_PRIVATE_KEY=${pem}`, 'GIPHY_API_KEY=emulator-giphy-key'].join('\n'));
  writeOwned('.env.demo-lociar', [
    'APPLE_TEAM_ID=TESTTEAM01',
    'APPLE_KEY_ID=TESTKEY001',
    'APPLE_CLIENT_ID=com.khankartal.lociar',
    `APPLE_AUTH_BASE_URL=http://127.0.0.1:${APPLE_STUB_PORT}`,
    `GIPHY_API_BASE_URL=http://127.0.0.1:${GIPHY_STUB_PORT}`,
  ].join('\n'));
}
